name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  deploy:
    name: 'Deploy on Node v${{ matrix.node }} ${{ matrix.os.name }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Ubuntu
            version: latest
        node: ['14']
        arch: [x64]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install npm@^8'
        run: npm install --global npm@8.3.1
      - name: Install
        run: npm ci --unsafe-perm
      - name: Publish tagged release to npm
        run: |
          npm i clean-package -g
          npm whoami
          npm run build
          npm run publish_tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}